workspace:
  base: /go/src
  path: github.com/crusttech/crust

kind: pipeline
name: crust

steps:
- name: build
  image: crusttech/api-builder:latest
  environment:
    CGO_ENABLED: 0
    GOOS: linux
    GOARCH: amd64
  commands:
  - go build -ldflags "-X github.com/crusttech/crust/internal/version.BuildTime=`date +%FT%T%z` -X github.com/crusttech/crust/internal/version.Version=`git describe --always --tags`" -o build/crust-$GOOS-$GOARCH cmd/crust/*.go
  - go build -ldflags "-X github.com/crusttech/crust/internal/version.BuildTime=`date +%FT%T%z` -X github.com/crusttech/crust/internal/version.Version=`git describe --always --tags`" -o build/crm-$GOOS-$GOARCH cmd/crm/*.go
  - go build -ldflags "-X github.com/crusttech/crust/internal/version.BuildTime=`date +%FT%T%z` -X github.com/crusttech/crust/internal/version.Version=`git describe --always --tags`" -o build/messaging-$GOOS-$GOARCH cmd/messaging/*.go
  - go build -ldflags "-X github.com/crusttech/crust/internal/version.BuildTime=`date +%FT%T%z` -X github.com/crusttech/crust/internal/version.Version=`git describe --always --tags`" -o build/system-$GOOS-$GOARCH cmd/system/*.go
  - go build -ldflags "-X github.com/crusttech/crust/internal/version.BuildTime=`date +%FT%T%z` -X github.com/crusttech/crust/internal/version.Version=`git describe --always --tags`" -o build/system-cli-$GOOS-$GOARCH cmd/system-cli/*.go

trigger:
  ref:
    - "refs/heads/**"
    - "refs/pull/**"
    - "refs/tags/**"

---
workspace:
  base: /go/src
  path: github.com/crusttech/crust

kind: pipeline
name: integration

steps:
- name: build
  image: crusttech/api-builder:latest
  environment:
    CGO_ENABLED: 0
    GOOS: linux
    GOARCH: amd64
    CI: circleci
    AUTH_OIDC_ENABLED: 0
    AUTH_JWT_SECRET: bRxJ37sJ6Qu4
  commands:
  - go fmt ./cmd/... ./internal/... ./crm/... ./messaging/... ./system/...
  - make mocks
  - wait-for-it.sh -t 60 --strict crust-db:3306 -- echo "Crust DB1 is up"
  - gotest -v --tags="migrations" ./system/db/... ./crm/db/... ./messaging/db/...
  - gotest -v --tags="unit integration external" ./internal/... ./system/... ./crm/... ./messaging/...

services:
- name: crust-db
  image: percona:8.0
  ports:
    - 3306
  environment:
    MYSQL_ROOT_PASSWORD: bRxJ37sJ6Qu4
    MYSQL_DATABASE: crust
    MYSQL_USER: crust
    MYSQL_PASSWORD: crust

trigger:
